### ISSUE TITLE
Intuition behind R_{ab} term in the augmentation term

### ISSUE THREAD

**Issue by kane9530** [Listen-lei/AttentionVGAE-main#1]
Hi there, thank you very much for developing this tool! 

I would like your help to understand better the intuition behind the $R_{ab}$ term (equation 2) used in the augmentation gene expression matrix (equation 1). I note that it is essentially a dissimilarity score, defined via 1 - cosine similarity: if 2 spots differ in the variation from their gene expression average, then $R_{ab}$ would be large. 

My 2 questions are:
1. Has there been ablation experiments performed without the term, and if the addition of this term significantly improves the quality of the augmented matrix?
2. What is the (approximate) physical interpretation of this term, or the motivation behind its inclusion? Why would we want to emphasise a neighboring spot if it has a different expression profile in terms of its variation from its mean? Does this help to the capture the local tissue microenvironment?

Thank you!

Best wishes,
Kane

**Comment by Listen-lei** [comment]
Hello, I'm glad you are interested in our work.

First of all, for the second problem, the essence of this formula is to calculate the correlation or the degree of correlation between two vectors, and if they're close, the value of R is closer to 1. As for the motivation behind it, it is that in reality, there are interactions in the local tissue microenvironment, and the ST data used has problems such as insufficient resolution, which aggravates more poor gene expression quality, which is bad news for spatial domain detection. If the expression of neighbor points has different expression curves on the mean, it is possible that there are differences in the local tissue microenvironment, which contributes to revealing the heterogeneity in tumor tissues. Therefore, we believe that it can help to correct low-quality gene expression, thereby affecting the capture of the local tissue microenvironment to some extent.

Secondly, the first problem is that we have not conducted strict ablation experiments on formula 2 in our work, in fact, it has been determined at the beginning of our work. The purpose of adding it is more to further correct the expression of low-quality genes through the information of neighbor points.The latest HD technology can improve the resolution to the single-cell level, so I think this method is not meaningful for high resolution ST data, and the wheel of technological development is rolling.

**Comment by kane9530** [comment]
Thank you @Listen-lei for your response! 

Regarding your first point, if I understood the formula correctly, the value of R should be closer to 0 (instead of 1), if 2 vectors are similar to each other? The term is 1- a cosine similarity score right?

So as I see it, you are saying that the formula aims to incorporate information from dissimilar neighbors into a spot's expression profile, to augment it with information from the heterogeneous local microenvironment. This helps to correct the lack of resolution & sparsity in some ST datasets, but its utility may decrease with techonlogical improvements in capture resolution and gene detection ability. I hope this captures your point. Thank you!
